### ISSUE TITLE
Support for NOMe-seq in dmtools

### ISSUE THREAD

**Issue by enzeas** [ZhouQiangwei/dmtools#1]
I would like to express my appreciation for the outstanding functionality provided by the DNA Methylation tools, which have proven to be an invaluable resource in terms of both space and time efficiency.

I kindly request an enhancement to the tool's functionality by adding support for NOMe-seq, specifically for WCG and GCH contexts. Incorporating support for WCG and GCH during the format conversion process would greatly enhance the tool's versatility and utility.

NOMe-Seq is a single-molecule, high-resolution nucleosome positioning assay. This method is based on the ability of the GpC methyltransferase M.CviPI to methylate GpC sites that are not bound by nucleosomes, to create a digital footprint of nucleosome positioning. M.CviPI can map nucleosome positions at CpG-poor promoters, irrespective of their endogenous methylation status. In this method, native chromatin is treated with M.CviPI, following which the DNA is treated with sodium bisulfite and subjected to WGBS. From these data, CpG methylation patterns as well as nucleosome-free regions (GpC methylation) can be identified.1

I would like to extend my gratitude to the developers for their excellent work on this tool, and I look forward to the possibility of seeing NOMe-seq support integrated into future releases.

Thank you for your time and consideration.

**Comment by ZhouQiangwei** [comment]
Hi,
Thank you for your appreciative words regarding the DNA Methylation tools and your insightful request for an enhancement. We are thrilled to learn about the positive impact our tools have had on your research.

Your detailed explanation of NOMe-seq and the specific contexts (WCG and GCH) you would like to see supported in the tool's functionality is invaluable. We understand the significance of NOMe-seq in providing high-resolution nucleosome positioning, and we are committed to enhancing our tool to accommodate these requirements.

I want to assure you that our team is actively working on incorporating NOMe-seq support, including the mentioned contexts (WCG and GCH), in our upcoming releases. We appreciate your patience and understanding as we strive to make these improvements.

Your feedback is crucial to our continuous improvement, and we are grateful for your contribution to the evolution of our tools. If you have any additional suggestions or insights, please don't hesitate to share them with us.

Thank you once again for your support.

**Comment by ZhouQiangwei** [comment]
a quick question, as I'm not very familiar with NOMe-Seq data. What downstream analyses and visualizations are needed?

**Comment by enzeas** [comment]
Thank you for your quick response and interest in NOMe-Seq data. We appreciate your engagement with the project.

In our NOMe-Seq analyses, we rely on downstream analysis pipelines as outlined in the following articles:

Guo, H., et al. (2017). "DNA methylation and chromatin accessibility profiling of mouse and human fetal germ cells." Cell Research, 27(2), 165–183. [DOI: 10.1038/cr.2016.128]
Lin, J., et al. (2023). "scNanoCOOL-seq: A long-read single-cell sequencing method for multi-omics profiling within individual cells." Cell Research. [DOI: 10.1038/s41422-023-00873-5]

These pipelines, available at [NOMeSeq GitHub](https://github.com/huboqiang/NOMeSeq) and [scNanoCOOL-seq GitHub](https://github.com/sherryxuePKU/scNanoCOOL-seq), utilize the methylpy tool (https://github.com/yupenghe/methylpy) for extracting methylation state, saving the data in gzip format as described [here](https://github.com/yupenghe/methylpy#output-format).

Furthermore, we employ the nucleosome-depleted region (NDR) calling script, available at [scNanoCOOL-seq NDR script](https://github.com/sherryxuePKU/scNanoCOOL-seq/blob/main/bin/NDR/script/bulk_test2_v3p.py).

Should you have any more questions or need further clarification, please feel free to ask.

**Comment by ZhouQiangwei** [comment]
Hi,

The new version has added support for NOMe-seq data, which can be utilized through the 'dmtools bam2dm' command with the '--NoMe' parameter. As I currently don't have suitable NOMe data, it has not been systematically tested. Feel free to give it a try, and if you encounter any issues or have specific requirements, please don't hesitate to contact me at any time.
Thanks.
