### ISSUE TITLE
Question about storage format

### ISSUE THREAD

**Issue by kdkorthauer** [ZhouQiangwei/dmtools#2]
Just a quick question about the storage format. Why not include integer counts of methylated reads instead of a float methylation level? The float value storage takes up more file space and could introduce ambiguities due to rounding that would prevent modeling the WGBS data using count models. Thanks!

**Comment by ZhouQiangwei** [comment]
Hi,
Because we consider that checking the DNA methylation level at specific sites does not require additional computation, especially during visualization. I understand your point, and we will consider adding a storage result that retains only the number of reads.
